CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE,
  email TEXT UNIQUE,
  password_hash TEXT,
  display_name TEXT,
  bio TEXT DEFAULT 'Hello, I am a new user!',
  avatar_url TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=j2st',
  banner_url TEXT DEFAULT '',
  role TEXT DEFAULT 'user',
  links TEXT DEFAULT '[]',
  badges TEXT DEFAULT '[]',
  avatar_frame_color TEXT DEFAULT '#ffffff',
  icon_color TEXT DEFAULT '#ffffff',
  badge_bg_color TEXT DEFAULT 'rgba(255, 255, 255, 0.1)',
  accent_color TEXT DEFAULT '#3498db',
  base_font TEXT DEFAULT 'Inter',
  base_font_color TEXT DEFAULT '#ffffff',
  name_font TEXT DEFAULT 'Inter',
  name_font_color TEXT DEFAULT '#ffffff',
  bio_font TEXT DEFAULT 'Inter',
  bio_font_color TEXT DEFAULT '#cccccc',
  card_style TEXT DEFAULT 'glass',
  hover_text TEXT DEFAULT 'Click to interact',
  link_hover_anim TEXT DEFAULT 'float',
  glitch_avatar BOOLEAN DEFAULT 0,
  profile_music_url TEXT DEFAULT '',
  bg_effect TEXT DEFAULT 'none',
  entry_anim TEXT DEFAULT 'fade-in',
  tilt_3d BOOLEAN DEFAULT 1,
  custom_cursor_url TEXT DEFAULT '',
  views INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
